---
- name: Obtain apigee-provision status
  stat:
    path: '{{ apigee_provision_dir }}'
  register: apigee_provision_status

- name: Apigee provision installation
  shell: '{{ apigee_service }} apigee-provision install'
  when: not apigee_provision_status.stat.exists

- name: Apigee organization setup
  shell: '{{ apigee_service }} apigee-provision setup-org -f {{ onboarding_config_file_path }}'
  ignore_errors: yes
