---

- name: Checking for Management Server Port
  register: ms_ext_mgmt_port_status
  ignore_errors: true
  wait_for:
    port: '{{ ms_ext_mgmt_port }}'
    host: '{{ local_address }}'
    timeout: 1

- name: Management Server Port Status report
  debug:
    var: ms_ext_mgmt_port_status

- name: Management server is not running
  fail:
    msg: "Management server is not running"
  when: ms_ext_mgmt_port_status | failed

- include: with_no_proxy.yml
  when: http_proxy is not defined and https_proxy is not defined

- include: with_proxy.yml
  when: http_proxy is defined and https_proxy is defined

- name: Apigee organization setup with no proxy
  shell: '{{ apigee_service }} apigee-provision setup-org -f {{ onboarding_config_file_path }}'
  ignore_errors: yes
